[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 4 }
opacity = 0.94
blur = true

[font]
size = 18
offset = { x = 0, y = 4 }

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "HackGen35 Console NF"

[scrolling]
history = 100000
multiplier = 5

