hs = hs

hs.hotkey.bind({"cmd"}, "Escape", function ()
    hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind({"cmd"}, "1", function ()
    hs.application.launchOrFocus("Cider")
end)
hs.hotkey.bind({"cmd"}, "2", function ()
    hs.application.launchOrFocus("Simulator")
end)
hs.hotkey.bind({"cmd"}, "3", function ()
    hs.application.launchOrFocus("Duckie")
end)
hs.hotkey.bind({"cmd"}, "4", function ()
    hs.application.launchOrFocus("Google Tasks")
end)
hs.hotkey.bind({"cmd"}, "5", function ()
    hs.application.launchOrFocus("Google Chat")
end)
hs.hotkey.bind({"cmd"}, "6", function ()
    hs.application.launchOrFocus("Google Calendar")
end)
hs.hotkey.bind({"cmd"}, "`", function ()
    hs.application.launchOrFocus("iTerm")
end)

local window_management = require "modules.window_manager"

hs.hotkey.bind({"option"}, "Left", window_management.moveWindowLeft)
hs.hotkey.bind({"option"}, "Right", window_management.moveWindowRight)
hs.hotkey.bind({"option"}, "Up", window_management.maximizeWindow)
hs.hotkey.bind({"optionn"}, "Down", window_management.minimizeWindow)
hs.hotkey.bind({"option", "shift"}, "Left", window_management.moveWindowNextScreen)
hs.hotkey.bind({"option", "shift"}, "Right", window_management.moveWindowPrevScreen)
