hs = hs

hs.hotkey.bind({"cmd"}, "Escape", function ()
    hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind({"cmd"}, "1", function ()
    hs.application.launchOrFocus("Cider")
end)
hs.hotkey.bind({"cmd"}, "2", function ()
    hs.application.launchOrFocus("Gemini")
end)
hs.hotkey.bind({"cmd"}, "3", function ()
    hs.application.launchOrFocus("Duckie")
end)
hs.hotkey.bind({"cmd"}, "4", function ()
    hs.application.launchOrFocus("Google Calendar")
end)
hs.hotkey.bind({"cmd"}, "5", function ()
    hs.application.launchOrFocus("Google Chat")
end)
