
# tap repositories and their packages

tap homebrew/core
brew abseil
brew aom
brew aribb24
brew assimp
brew autoconf
brew automake
brew bash-completion
brew bdw-gc
brew bitwarden-cli
brew boost
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew certifi
brew cgns
brew chezmoi
brew cjson
brew cmake
brew coreutils
brew dav1d
brew dbus
brew diffutils
brew docker
brew docker-completion
brew docker-compose
brew double-conversion
brew ed
brew eigen
brew fdk-aac
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gawk
brew gcc
brew gettext
brew gh
brew giflib
brew git
brew glib
brew gmp
brew gnu-sed
brew gnu-tar
brew gnutls
brew go
brew graphite2
brew grep
brew guile
brew gzip
brew harfbuzz
brew hdf5
brew highway
brew hunspell
brew hyperfine
brew icu4c@77
brew imagemagick
brew imath
brew ipython
brew isl
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew jsoncpp
brew jupyterlab
brew lame
brew leptonica
brew libaec
brew libarchive
brew libass
brew libb2
brew libbluray
brew libde265
brew libdeflate
brew libevent
brew libharu
brew libheif
brew libidn2
brew liblqr
brew libmicrohttpd
brew libmng
brew libmpc
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libraw
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew lz4
brew lzo
brew m4
brew mbedtls
brew md4c
brew miniupnpc
brew mosh
brew mpdecimal
brew mpfr
brew mpg123
brew nasm
brew ncurses
brew netcdf
brew nettle
brew nlohmann-json
brew node
brew node@20
brew ntfy
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre2
brew pdm
brew pixlet
brew pixman
brew pkgconf
brew pnpm
brew podman
brew proj
brew protobuf
brew pugixml
brew pyqt
brew python@3.12
brew python@3.13
brew qt
brew rav1e
brew readline
brew restic
brew rubberband
brew ruby
brew rye
brew scrcpy
brew sdl12-compat
brew sdl2
brew shared-mime-info
brew shtool
brew snappy
brew speex
brew sqlite
brew srt
brew svt-av1
brew swiftlint
brew syncthing
brew task
brew task@2
brew tesseract
brew texi2html
brew theora
brew tmux
brew transmission-cli
brew tree
brew unbound
brew utf8cpp
brew utf8proc
brew uv
brew vim
brew vit
brew vtk
brew wakeonlan
brew watch
brew webp
brew wget
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew yarn
brew yt-dlp
brew zeromq
brew zimg
brew zoxide
brew zstd

tap homebrew/cask
cask adobe-creative-cloud
cask alacritty
cask android-platform-tools
cask azookey
cask bitwarden
cask coteditor
cask discord
cask font-hackgen
cask gcloud-cli
cask google-chrome
cask google-japanese-ime
cask iterm2
cask karabiner-elements
cask lm-studio
cask maccy
cask menumeters
cask notion
cask obs
cask obsidian
cask raycast
cask slack
cask stats
cask syncthing-app
cask visual-studio-code
cask vlc
cask xquartz

tap homebrew/bundle

tap homebrew-ffmpeg/ffmpeg

tap rcmdnk/file
brew brew-file

tap rfushimi/tools

tap tidbyt/tidbyt

# Other Cask applications
cask kindle

# App Store applications
appstore 302584613 Amazon Kindle (7.54)
appstore 1168254295 AmorphousDiskMark (4.0.1)
appstore 1352778147 Bitwarden (2026.2.1)
appstore 1500855883 CapCut (8.3.0)
appstore 1024640650 CotEditor (6.2.6)
appstore 640199958 Developer (10.8.3)
appstore 1380563956 Dictionaries (1.4)
appstore 975937182 Fantastical (4.1.10)
appstore 1358823008 Flighty (4.7.3)
appstore 682658836 GarageBand (10.4.13)
appstore 1111570163 GrandPerspective (3.6.4)
appstore 975890633 HotKey (1.5)
appstore 408981434 iMovie (10.4.4)
appstore 409183694 Keynote (14.5)
appstore 539883307 LINE (26.0.2)
appstore 409203825 Numbers (14.5)
appstore 409201541 Pages (14.5)
appstore 545519333 Prime Video (10.120.1)
appstore 1475387142 Tailscale (1.94.1)
appstore 425424353 The Unarchiver (4.3.9)
appstore 904280696 Things3 (3.22.11)
appstore 1295203466 Windows App (11.3.2)
appstore 497799835 Xcode (26.3)
